# Generated by Django 5.2 on 2025-04-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fever', models.BooleanField(default=False)),
                ('fatigue', models.BooleanField(default=False)),
                ('chills_or_sweating', models.BooleanField(default=False)),
                ('loss_of_appetite', models.BooleanField(default=False)),
                ('cough', models.BooleanField(default=False)),
                ('shortness_of_breath', models.BooleanField(default=False)),
                ('sore_throat', models.BooleanField(default=False)),
                ('runny_or_stuffy_nose', models.BooleanField(default=False)),
                ('nausea_or_vomiting', models.BooleanField(default=False)),
                ('diarrhea', models.BooleanField(default=False)),
                ('abdominal_pain', models.BooleanField(default=False)),
                ('headache', models.BooleanField(default=False)),
                ('body_aches_muscle_pain', models.BooleanField(default=False)),
                ('joint_pain_or_stiffness', models.BooleanField(default=False)),
                ('chest_pain', models.BooleanField(default=False)),
                ('throat_pain', models.BooleanField(default=False)),
                ('ear_pain', models.BooleanField(default=False)),
                ('eye_pain_or_sensitivity', models.BooleanField(default=False)),
                ('dizziness_or_lightheadedness', models.BooleanField(default=False)),
                ('nerve_pain', models.BooleanField(default=False)),
                ('rash_or_skin_changes', models.BooleanField(default=False)),
                ('swollen_lymph_nodes', models.BooleanField(default=False)),
                ('pregnancy', models.BooleanField(default=False)),
                ('injury_concerning_bone', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
