# Generated by Django 5.2 on 2025-04-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthrecord',
            old_name='age',
            new_name='Age',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='abdominal_pain',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='body_aches_muscle_pain',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='chest_pain',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='chills_or_sweating',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='cough',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='diarrhea',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='dizziness_or_lightheadedness',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='ear_pain',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='eye_pain_or_sensitivity',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='fatigue',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='fever',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='headache',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='injury_concerning_bone',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='joint_pain_or_stiffness',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='loss_of_appetite',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='nausea_or_vomiting',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='nerve_pain',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='pregnancy',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='rash_or_skin_changes',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='runny_or_stuffy_nose',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='shortness_of_breath',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='sore_throat',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='swollen_lymph_nodes',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='throat_pain',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='Abdominal Pain',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='Body Aches & Muscle Pain',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='Chest Pain',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='Chills or Sweating',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='Dizziness or Lightheadedness',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='Ear Pain',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='Eye Pain or Sensitivity',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='Injury concerning bone',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='Joint Pain or Stiffness',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='Loss of Appetite',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='Nausea or Vomiting',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='Nerve Pain (Tingling, Burning, Sharp Pain)',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='Rash or Skin Changes',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='Runny or Stuffy Nose',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='Shortness of Breath',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='Sore Throat',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='Swollen Lymph Nodes',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='Throat Pain',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='Cough',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='Diarrhea',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='Fatigue',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='Fever',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='Headache',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='Pregnancy',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
