# Generated by Django 5.2 on 2025-04-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_rename_age_healthrecord_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='Abdominal Pain',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='Body Aches & Muscle Pain',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='Chest Pain',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='Chills or Sweating',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='Cough',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='Diarrhea',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='Dizziness or Lightheadedness',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='Ear Pain',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='Eye Pain or Sensitivity',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='Fatigue',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='Fever',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='Headache',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='Injury concerning bone',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='Joint Pain or Stiffness',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='Loss of Appetite',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='Nausea or Vomiting',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='Nerve Pain (Tingling, Burning, Sharp Pain)',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='Pregnancy',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='Rash or Skin Changes',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='Runny or Stuffy Nose',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='Shortness of Breath',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='Sore Throat',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='Swollen Lymph Nodes',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='Throat Pain',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', null=True),
        ),
    ]
